### PR TITLE
Deprovision etherpad-lite

### PR DESCRIPTION
**Pull request by andrewda**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
```
$ git ls-files | grep etherpad
test/cookbooks/osl-nginx-test/recipes/etherpad.rb
```

**Review by ramereth — APPROVED** [review]
Please do a minor bump on `~`

**Comment by andrewda** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v4.2.0.  Have a nice day!

**Pull request merged**
