### PR TITLE
Use stable osl-nagios branch to fix osl-nrpe dependency

### PR DESCRIPTION
**Pull request by captntuttle**
https://github.com/osuosl-cookbooks/osl-apache/pull/38

### CODE REVIEW

**Comment by armiller** [comment]
:+1:

**Comment by ramereth** [comment]
:+1:

**Comment by jordane** [comment]
+1

**Comment by fahlmant** [comment]
@captntuttle Is there a reason this was closed?

**Comment by captntuttle** [comment]
I failed to merge it for whatever reason. When I looked at it I thought 
https://github.com/osuosl-cookbooks/osl-nginx/commit/8e8ceb79acf9530da53f0d1f7dbd85642c6ea2ba 
obsoleted this PR.

**Comment by fahlmant** [comment]
@captntuttle Usually you should leave a comment as to why you closed a PR

**Comment by captntuttle** [comment]
Yeah, that makes sense. Will do next time.

**Pull request closed without merging**
