### PR TITLE
Chef 15 fixes

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by ramereth** [comment]
[Chef 15 - osl-nginx](https://trello.com/c/wIyY9RVn/1799-chef-15-osl-nginx)

**Comment by TheREK3R** [comment]
minor bump *

**Comment by TheREK3R** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v3.2.0.  Have a nice day!

**Pull request merged**
